
device: cuda
batch_size: 32
data_dir: onedrive_local/research/material_liu/data
model_dir: onedrive_local/research/material_liu/model
load_ae: False
dataset: chair_set.npy
output_folder: output/
save_results: True
latent_size: 128       # bottleneck size of the AE
ae_epoch: 1001
gan_epoch: 100
gan_batch: 64
lambda_gp: 10
